# Generated by Django 3.0.6 on 2020-05-30 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_subject', models.CharField(help_text='会计科目', max_length=50, unique=True)),
                ('debit_balance', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='CashOnHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(default=datetime.date.today)),
                ('serial_number', models.IntegerField(default=1)),
                ('lucre', models.FloatField()),
                ('balance', models.FloatField()),
                ('summary', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('opposite_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.AccountingSubject')),
            ],
        ),
    ]
