# Generated by Django 3.0.7 on 2020-07-18 04:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountingsubject', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOnHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('operation_date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('serial_number', models.IntegerField(default=65535, help_text='( >=1 )', verbose_name='序号')),
                ('lucre', models.FloatField(help_text='( >0 )', verbose_name='金额')),
                ('balance', models.FloatField(editable=False)),
                ('summary', models.CharField(max_length=255)),
                ('opposite_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountingsubject.AccountingSubject', verbose_name='会计科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_cash_on_hand',
                'ordering': ['operation_date', 'serial_number'],
            },
        ),
    ]
