# Generated by Django 3.0.6 on 2020-05-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountingsubject',
            table='accounting_subject',
        ),
    ]
