# Generated by Django 3.0.7 on 2020-07-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashonhand',
            name='user',
        ),
    ]
