# Generated by Django 3.0.6 on 2020-05-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20200530_1902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountingsubject',
            table='cash_accounting_subject',
        ),
        migrations.AlterModelTable(
            name='cashonhand',
            table='cash_cash_on_hand',
        ),
    ]
