# Generated by Django 3.0.6 on 2020-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20200530_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashonhand',
            name='balance',
            field=models.FloatField(editable=False),
        ),
    ]
