# Generated by Django 3.0.7 on 2020-06-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20200530_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('serial_number', models.IntegerField(default=1, verbose_name='sequence')),
                ('lucre', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cashonhand',
            name='opposite_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.AccountingSubject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='cashonhand',
            name='serial_number',
            field=models.IntegerField(default=1, verbose_name='sequence'),
        ),
    ]
