# Generated by Django 3.0.7 on 2020-07-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('accounting_subject', models.CharField(help_text='会计科目', max_length=50, unique=True)),
                ('debit_balance', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cash_accounting_subject',
            },
        ),
    ]
